Repository pokt-network/shannon-sdk, pull requests merged in 2024-06, with the labels that each got.

#8 Refactor move app client
  application.go
  clients/account.go
  clients/application.go
  clients/block.go
  clients/params.go
  clients/relay.go
  clients/session.go
  clients/signer.go
Labels: enhancement

#4 [RPC] Add REST RPCType detection and error reply formatting
  sdk/sdk.go
  types/jsonrpc.go
  types/request.go
  types/response.go
  types/rest.go
  types/rpc_errors.go
Labels: enhancement

#5 [Docs] Update SDK docs
  README.md
Labels: documentation

#9 refactor: remove redundant application client
  application.go
  clients/application.go
  sdk/interface.go
  sdk/sdk.go
Labels: enhancement

#6 [CI] Add ci workflows
  .github/ISSUE_TEMPLATE/issue.md
  .github/pull_request_template.md
  .github/workflows/reviewdog.yml
  .github/workflows/run-tests.yml
  Makefile
Labels: enhancement

#11 [Helpers] Add copy header helper
  README.md
  types/types.go
Labels: enhancement

#3 [LeanClient] Add SupplierAddress to RelayRequestMetadata
  go.mod
  go.sum
  sdk/sdk.go
Labels: enhancement

#10 Refactor: move blocks client
  README.md
  block.go
  block_test.go
  clients/block.go
  sdk/interface.go
  sdk/sdk.go
  types/codec_test.go
  types/request.go
  types/response.go
Labels: enhancement

#14 add linter and fix discovered issues
  .github/workflows/run-tests.yml
  .golangci.yml
  block_test.go
  sdk/sdk.go
  types/request.go
  types/response.go
Labels: CI

#12 Refactor move session client
  clients/session.go
  sdk/interface.go
  sdk/sdk.go
  session.go
  session_test.go
  types/types.go
Labels: enhancement

#15 Refactor ring, sign, and relay functionality
  account.go
  application.go
  clients/account.go
  clients/params.go
  clients/relay.go
  clients/signer.go
  relay.go
  relay_test.go
  sdk/interface.go
  sdk/sdk.go
  signer.go
Labels: enhancement

#18 fix: Restore CopyToHTTPHeader
  types/header.go
Labels: enhancement

#20 fix: register codec types
  account.go
Labels: bug

#19 [Docs] Readme rewrite
  README.md
  account.go
  application.go
  block.go
  clients/account.go
  clients/params.go
  clients/relay.go
  clients/session.go
  clients/signer.go
  go.mod
  go.sum
  relay.go
  relay_test.go
  sdk/interface.go
  sdk/sdk.go
  session.go
  session_test.go
  signer.go
  types/header.go
  types/types.go
Labels: documentation
